### ISSUE TITLE
Does this work need huge GPU memory?

### ISSUE THREAD

**Issue by lizekui** [edward3862/CariMe-pytorch#4]

**Comment by lizekui** [comment]
This work is really fantastic! 
But when I run 
`!python main_generate_single_image.py --model_path_warper pretrained/warper.pt --model_path_styler pretrained/styler.pt --input_path /content/test.png --generate_num 5 --scale 1.0 `

I receive the follow error:
```
load warper:  pretrained/warper.pt
load styler:  pretrained/styler.pt
Traceback (most recent call last):
  File "main_generate_single_image.py", line 55, in <module>
    img_style = styler(img_p, s)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/CariMe-pytorch/networks/styler.py", line 165, in forward
    output = self.gen(img_p, s)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/CariMe-pytorch/networks/styler.py", line 105, in forward
    content, _ = self.encode(img_p)
  File "/content/CariMe-pytorch/networks/styler.py", line 95, in encode
    content = self.encoder_c(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/CariMe-pytorch/networks/styler.py", line 23, in forward
    return self.model(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/CariMe-pytorch/networks/modules.py", line 212, in forward
    x = self.conv(self.pad(x))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 353, in forward
    return self._conv_forward(input, self.weight)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 350, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 15.90 GiB total capacity; 14.95 GiB already allocated; 199.75 MiB free; 15.01 GiB reserved in total by PyTorch)
```
But I tried to print memory status before run this line, nvidia-smi return :

``` 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   31C    P0    25W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+ 
```

So I guess maybe `main_generate_single_image.py` initialization need 14.95 GB? Any thing I did is wrong?

Please help me, thanks!

**Comment by edward3862** [comment]
Hello, I found the same problem when running the code using an RTX 2080Ti GPU with about 11GB memory.

I reset the `generate_num` to 3 and everything goes right. I think the problem is caused by some unreleased memory in the loop. You can decrease the number of generated images and try again:)

If you find anything that can better solve the problem, please feel free to tell me. Thank you!

**Comment by lizekui** [comment]
hah that's a good idea and when I decrease `generate_num` until to 1, the code does not feed back `out of memory`, So I guess maybe some wrong with my input image.

I found my input image is `1024*1024` size, bigger than  samples' size (`256*256`) finally. 

Then I shrinked input image size and everything return to OK! 

Thanks @edward3862 !
